version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      # Install dependencies
      - run:
          name: install-dependencies
          command: npm install
      # Test
      - run:
          name: test
          command: npm test
