name: snapshots

on: [pull_request, pull_request_target]

jobs:
  snapshots:
    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --non-interactive

      - name: Test with update-snapshots
        run: AVA_FORCE_CI="not-ci" yarn ava --verbose --update-snapshots

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.4.1
        with:
          commit_message: "test: update snapshots"
          file_pattern: "*.snap *.md"
